// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefConnect.Models;

#nullable disable

namespace RefConnect.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RefConnect.Models.Champioship", b =>
                {
                    b.Property<string>("idCampionat")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("numeCampionat")
                        .HasColumnType("longtext");

                    b.Property<string>("tara")
                        .HasColumnType("longtext");

                    b.HasKey("idCampionat");

                    b.ToTable("Champioships");
                });

            modelBuilder.Entity("RefConnect.Models.Comment", b =>
                {
                    b.Property<string>("idComentariu")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("continut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dataPostarii")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("idPostare")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idComentariu");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RefConnect.Models.GroupChat", b =>
                {
                    b.Property<string>("idChat")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("numeChat")
                        .HasColumnType("longtext");

                    b.HasKey("idChat");

                    b.ToTable("GroupChats");
                });

            modelBuilder.Entity("RefConnect.Models.Match", b =>
                {
                    b.Property<string>("idMeci")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("dataMeciului")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("echipaGazda")
                        .HasColumnType("longtext");

                    b.Property<string>("echipaOaspeti")
                        .HasColumnType("longtext");

                    b.Property<string>("locatie")
                        .HasColumnType("longtext");

                    b.Property<int>("scorGazda")
                        .HasColumnType("int");

                    b.Property<int>("scorOaspeti")
                        .HasColumnType("int");

                    b.Property<string>("stadion")
                        .HasColumnType("longtext");

                    b.HasKey("idMeci");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("RefConnect.Models.Post", b =>
                {
                    b.Property<string>("idPostare")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("descriere")
                        .HasColumnType("longtext");

                    b.Property<string>("idUser")
                        .HasColumnType("longtext");

                    b.Property<string>("linkVideo")
                        .HasColumnType("longtext");

                    b.HasKey("idPostare");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("RefConnect.Models.Team", b =>
                {
                    b.Property<string>("idEchipa")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("numeAntrenor")
                        .HasColumnType("longtext");

                    b.Property<string>("numeEchipa")
                        .HasColumnType("longtext");

                    b.Property<string>("numePresedinte")
                        .HasColumnType("longtext");

                    b.HasKey("idEchipa");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("RefConnect.Models.userArbitru", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("nume")
                        .HasColumnType("longtext");

                    b.Property<string>("prenume")
                        .HasColumnType("longtext");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.HasKey("userId");

                    b.ToTable("UserArbitri");
                });
#pragma warning restore 612, 618
        }
    }
}
